#pragma once

#pragma comment(lib, "freetype.lib")
#pragma comment(lib, "jpeg-static.lib")
#pragma comment(lib, "libcairo.lib")
#pragma comment(lib, "libexpat.lib")
#pragma comment(lib, "libfontconfig.lib")
#pragma comment(lib, "libiconv.lib")
#pragma comment(lib, "libpixman-1.lib")
#pragma comment(lib, "libpng16_static.lib")
#pragma comment(lib, "lzo2.lib")
#pragma comment(lib, "poppler-cpp.lib")
#pragma comment(lib, "poppler.lib")
#pragma comment(lib, "tiff.lib")
#pragma comment(lib, "turbojpeg-static.lib")
#pragma comment(lib, "zlib.lib")
